[package]
name = "galtrans-desktop"
version = "0.4.4"
description = "GalTrans player desktop interface"
authors = ["GalTrans contributors"]
edition = "2024"

[lib]
name = "galtrans_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
